DROP TABLE "ESBDBID".WANG_EVENT@
CREATE TABLE "ESBDBID".WANG_EVENT(
  "ID" BIGINT GENERATED ALWAYS AS IDENTITY(
    START WITH 1
   ,INCREMENT BY 1
   ,CYCLE
   ,MINVALUE 1
  )
 ,"UUID" VARCHAR(255)
 ,"PARENT_UUID" VARCHAR(255)
 ,"GLOBAL_UUID" VARCHAR(255)
 ,"EVENT_NAME" VARCHAR(255) NOT NULL
 ,"CREATION_TIME" TIMESTAMP NOT NULL
 ,"PROCESS_TIME" TIMESTAMP NOT NULL
)
@
--SELECT * FROM "ESBDBID".BEAM_EVENT@
--DELETE FROM "ESBDBID".BEAM_EVENT@