BEGIN
   IF EXISTS (SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = 'ESBDBID' AND TABNAME = 'ESB_MQQ_STATUS') THEN
      PREPARE stmt FROM 'DROP TABLE ESBDBID.ESB_MQQ_STATUS';
      EXECUTE stmt;
   END IF;
END
@
CREATE TABLE "ESBDBID".ESB_MQQ_STATUS(
  "ID" BIGINT GENERATED ALWAYS AS IDENTITY(
    START WITH 1
   ,INCREMENT BY 1
   ,CYCLE
   ,MINVALUE 1
  )
 ,"HOSTNAME" VARCHAR(255)
 ,"QUEUE_MANAGER" VARCHAR(255)
 ,"QUEUE" VARCHAR(255)
 ,"CURDEPTH" INTEGER
 ,"MAXDEPTH" INTEGER
 ,"IPPROCS" INTEGER
 ,"STATUS" VARCHAR(255)
 ,"STATUS_TIME" VARCHAR(255) NOT NULL
 ,"CREATED" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP
)
PARTITION BY RANGE (CREATED) (STARTING FROM ('2020-01-01-00.00.00.000000')
ENDING AT ('2029-12-31-00.00.00.000000') EVERY (6 MONTH)
)
@
