SELECT * FROM "ESBDBID".IIB_STATUS WHERE HOSTNAME = 'fsr3vlesb' AND INTEGRATION_NODE = 'EFIB01' AND INTEGRATION_SERVER = 'richard_wang'@
--DELETE FROM "ESBDBID".BEAM_EVENT@

--DELETE FROM "ESBDBID".IIB_STATUS WHERE HOSTNAME = 'fsr3vlesb' AND INTEGRATION_NODE = 'EFIB01' AND INTEGRATION_SERVER = 'yarlat'@