CREATE TABLE IF NOT EXISTS ESBDBID.ESB_MQ_STATUS(
ID BIGINT NOT NULL AUTO_INCREMENT,
HOSTNAME VARCHAR(255),
QUEUE_MANAGER VARCHAR(255),
STATUS VARCHAR(255),
STATUS_TIME VARCHAR(255) NOT NULL,
CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
)