CREATE TABLE IF NOT EXISTS ESBDBID.ESB_IIB_STATUS(
ID BIGINT NOT NULL AUTO_INCREMENT,
HOSTNAME VARCHAR(255),
INTEGRATION_NODE VARCHAR(255),
INTEGRATION_SERVER VARCHAR(255),
APPLICATION VARCHAR(255),
MESSAGE_FLOW VARCHAR(255),
STATUS VARCHAR(255),
STATUS_TIME VARCHAR(255) NOT NULL,
CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
)