CREATE TABLE IF NOT EXISTS ESBDBID.ESB_MQQ_STATUS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  HOSTNAME varchar(255) DEFAULT NULL,
  QUEUE_MANAGER varchar(255) DEFAULT NULL,
  QUEUE varchar(255) DEFAULT NULL,
  CURDEPTH int(11) DEFAULT NULL,
  MAXDEPTH int(11) DEFAULT NULL,
  IPPROCS int(11) DEFAULT NULL,
  STATUS varchar(255) DEFAULT NULL,
  STATUS_TIME varchar(255) NOT NULL,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
)
