CREATE TABLE IF NOT EXISTS ESB_MQ_STATUS(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
HOSTNAME VARCHAR(255),
QUEUE_MANAGER VARCHAR(255),
STATUS VARCHAR(255),
STATUS_TIME VARCHAR(255) NOT NULL,
CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)