CREATE TABLE IF NOT EXISTS ESB_FILE_STATUS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HOSTNAME VARCHAR(255),
    DIRECTORY VARCHAR(255),
    FILE_NAME VARCHAR(255),
    CHMOD VARCHAR(255),
    CHOWN VARCHAR(255),
    CHGRP VARCHAR(255),
    FILE_SIZE INTEGER,
    LAST_MODIFIED VARCHAR(255),
    STATUS VARCHAR(255),
    STATUS_TIME VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
