CREATE TABLE IF NOT EXISTS ESB_MQQ_STATUS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    HOSTNAME VARCHAR(255),
    QUEUE_MANAGER varchar(255),
    QUEUE varchar(255),
    CURDEPTH int,
    MAXDEPTH int,
    IPPROCS int,
    STATUS varchar(255),
    STATUS_TIME varchar(255) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
